"use client";
import { useMemo, useState } from "react";
import type { Product } from "@/lib/types";
import { ProductGrid } from "./ProductGrid";

export function CollectionPage({ title, description, products, filters, image }: { title:string; description:string; products:Product[]; filters:string[]; image:string }) {
  const [filter,setFilter]=useState("All"); const [sort,setSort]=useState("featured");
  const shown=useMemo(()=>{const filtered=filter==="All"?products:products.filter(p=>p.category===filter); return [...filtered].sort((a,b)=>sort==="low"?a.price-b.price:sort==="high"?b.price-a.price:Number(b.featured)-Number(a.featured))},[filter,sort,products]);
  return <><section className="relative h-[48vh] min-h-[420px] overflow-hidden"><img src={image} alt="" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#3B3028]/70 to-transparent"/><div className="container-site absolute inset-x-0 bottom-10 text-white"><p className="eyebrow text-[#D8C5A5]">The collection</p><h1 className="mt-3 text-7xl leading-none md:text-8xl">{title}</h1><p className="mt-4 max-w-lg text-sm leading-7 text-white/75">{description}</p></div></section><section className="section"><div className="container-site"><div className="mb-10 flex flex-col gap-5 border-b border-[#3B3028]/10 pb-6 md:flex-row md:items-center md:justify-between"><div className="flex flex-wrap gap-2">{["All",...filters].map(item=><button key={item} onClick={()=>setFilter(item)} className={`rounded-full border px-4 py-2 text-xs font-bold transition ${filter===item?"border-[#3B3028] bg-[#3B3028] text-white":"border-[#3B3028]/15 hover:border-[#3B3028]"}`}>{item}</button>)}</div><label className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider">Sort <select value={sort} onChange={e=>setSort(e.target.value)} className="rounded-full border border-[#3B3028]/15 bg-white px-4 py-2 text-xs normal-case"><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label></div>{shown.length?<ProductGrid products={shown}/>:<p>No products in this category yet.</p>}</div></section></>;
}
