"use client";
import { useState } from "react";
import type { Product } from "@/lib/types";
import { useCart } from "@/components/cart/CartProvider";

export function ProductDetail({ product }: { product:Product }) {
  const [color,setColor]=useState(product.colors[0]); const [quantity,setQuantity]=useState(1); const [image,setImage]=useState(product.images[0]); const {addItem}=useCart();
  return <section className="section pt-8 md:pt-12"><div className="container-site grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:gap-16"><div><div className="aspect-[4/5] overflow-hidden rounded-[26px] bg-[#F5F0E8] md:aspect-[5/4]"><img src={image} alt={product.name} className="h-full w-full object-cover"/></div><div className="mt-3 grid grid-cols-3 gap-3">{product.images.map((src,i)=><button key={src} onClick={()=>setImage(src)} aria-label={`View product image ${i+1}`} className={`aspect-square overflow-hidden rounded-xl border-2 ${image===src?"border-[#B96D4A]":"border-transparent"}`}><img src={src} alt="" className="h-full w-full object-cover"/></button>)}</div></div><div className="lg:sticky lg:top-32 lg:self-start"><p className="eyebrow text-[#B96D4A]">{product.category} · For {product.animal}s</p><h1 className="mt-4 text-5xl leading-none md:text-7xl">{product.name}</h1><p className="mt-5 text-xl font-bold">${product.price.toFixed(2)}</p><p className="mt-6 text-sm leading-7 opacity-65">{product.longDescription}</p><div className="mt-8"><div className="flex justify-between text-xs font-bold uppercase tracking-wider"><span>Colour</span><span className="opacity-50">{color}</span></div><div className="mt-3 flex gap-3">{product.colors.map(item=><button key={item} onClick={()=>setColor(item)} aria-label={`Select ${item}`} className={`h-9 w-9 rounded-full border-2 p-1 ${color===item?"border-[#3B3028]":"border-transparent"}`}><span className="block h-full w-full rounded-full border border-[#3B3028]/10" style={{background:product.colorHex[item]}}/></button>)}</div></div><div className="mt-8 flex gap-3"><div className="flex min-w-32 items-center justify-between rounded-full border border-[#3B3028]/20 px-3"><button aria-label="Decrease quantity" className="p-2" onClick={()=>setQuantity(Math.max(1,quantity-1))}>−</button><span className="text-sm font-bold">{quantity}</span><button aria-label="Increase quantity" className="p-2" onClick={()=>setQuantity(quantity+1)}>+</button></div><button className="btn btn-dark flex-1" onClick={()=>addItem(product,color,quantity)}>Add to bag · ${(product.price*quantity).toFixed(2)}</button></div><p className="mt-3 text-center text-[11px] opacity-50">In stock · Delivery available across Lebanon</p><div className="mt-9 border-t border-[#3B3028]/10"><Details title="Product features"><ul className="list-disc space-y-2 pl-4">{product.features.map(f=><li key={f}>{f}</li>)}</ul></Details><Details title="Materials & dimensions"><p>{product.materials}</p><p className="mt-2">{product.dimensions}</p></Details><Details title="Care instructions"><p>{product.careInstructions}</p></Details><Details title="Delivery information"><p>Delivery is available across Lebanon. We will confirm timing and delivery fees with you on WhatsApp.</p></Details></div></div></div></section>;
}
function Details({title,children}:{title:string;children:React.ReactNode}){return <details className="group border-b border-[#3B3028]/10 py-5" open={title==="Product features"}><summary className="flex cursor-pointer list-none items-center justify-between text-xs font-bold uppercase tracking-wider">{title}<span className="text-xl group-open:rotate-45">+</span></summary><div className="pt-4 text-sm leading-6 opacity-65">{children}</div></details>}
