import type { Product } from "./types";

const img = {
  leash: "https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=1200&q=85",
  harness: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=1200&q=85",
  dogHome: "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=1200&q=85",
  dogWalk: "https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=1200&q=85",
  dogPlay: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=1200&q=85",
  catWindow: "https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&w=1200&q=85",
  catBasket: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=1200&q=85",
  catBowl: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=1200&q=85",
  catLounge: "https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?auto=format&fit=crop&w=1200&q=85",
  catPlay: "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?auto=format&fit=crop&w=1200&q=85",
};

const common = {
  inStock: true,
  colorHex: { Sand: "#D8C5A5", Terra: "#B96D4A", Olive: "#6F7654", Oat: "#E6D8C4", Clay: "#A95E41", Cedar: "#6A4836", Natural: "#D9C29F", Charcoal: "#4D4844" },
};

export const products: Product[] = [
  { ...common, id: "d1", slug: "nomad-rope-leash", name: "The Nomad Rope Leash", animal: "dog", category: "Walk", price: 38, description: "A soft, durable rope leash for everyday walks and weekend escapes.", longDescription: "Thoughtfully designed for easy morning strolls, mountain weekends and everything in between. The Nomad combines a comfortable hand feel with hardware you can trust.", images: [img.leash, img.dogWalk, img.dogHome], colors: ["Sand", "Terra", "Olive"], materials: "Cotton-blend rope, zinc alloy hardware", dimensions: "150 cm length · 1.2 cm diameter", features: ["Soft cotton-blend rope", "Comfortable hand loop", "Strong metal clasp", "Lightweight and durable", "Available in natural earth tones"], careInstructions: "Spot clean with mild soap. Air dry completely.", featured: true },
  { ...common, id: "d2", slug: "terra-walking-harness", name: "The Terra Walking Harness", animal: "dog", category: "Walk", price: 52, description: "A balanced, breathable harness made for comfortable exploring.", longDescription: "A secure everyday harness with a soft padded body and easy adjustment at the neck and chest.", images: [img.harness, img.dogWalk], colors: ["Terra", "Olive"], materials: "Recycled woven shell, breathable mesh lining", dimensions: "S–L · adjustable fit", features: ["Three-point adjustment", "Soft breathable lining", "Front and back lead rings", "Secure side-release buckle"], careInstructions: "Hand wash cool and lay flat to dry.", featured: true },
  { ...common, id: "d3", slug: "cedar-travel-mat", name: "The Cedar Travel Mat", animal: "dog", category: "Travel", price: 68, description: "A roll-up comfort mat for cafés, road trips and long weekends.", longDescription: "A practical portable place for your dog to settle, finished in a textured fabric that belongs in beautiful spaces.", images: [img.dogHome, img.dogWalk], colors: ["Cedar", "Oat"], materials: "Cotton canvas, recycled fill, leather strap", dimensions: "75 × 55 cm open", features: ["Quilted comfort", "Roll-and-carry design", "Water-resistant base", "Removable carry strap"], careInstructions: "Cold gentle wash. Remove strap before washing.", featured: true },
  { ...common, id: "d4", slug: "olive-treat-pouch", name: "The Olive Treat Pouch", animal: "dog", category: "Walk", price: 24, description: "A hands-free pouch that keeps rewards close without looking technical.", longDescription: "A compact everyday pouch for treats, keys and the tiny essentials that keep walks moving.", images: [img.dogWalk, img.dogPlay], colors: ["Olive", "Sand"], materials: "Waxed cotton canvas, cotton webbing", dimensions: "15 × 12 × 5 cm", features: ["Magnetic closure", "Adjustable waist strap", "Easy-clean lining", "Small key pocket"], careInstructions: "Wipe clean with a damp cloth.", featured: false },
  { ...common, id: "d5", slug: "play-knot", name: "The Jute Play Knot", animal: "dog", category: "Play", price: 18, description: "A satisfyingly simple tug toy in braided natural fibres.", longDescription: "A tactile play piece for supervised games, made with a quiet palette and sturdy braided form.", images: [img.dogPlay, img.harness], colors: ["Natural"], materials: "Braided jute and cotton", dimensions: "32 cm length", features: ["Natural fibres", "Comfortable grip", "Plastic-free", "Made for interactive play"], careInstructions: "Spot clean. Supervise play and replace if damaged.", featured: false },
  { ...common, id: "c1", slug: "hammock-window-bed", name: "The Hammock Window Bed", animal: "cat", category: "Sleep", price: 62, description: "A sun-catching perch for naps, watching and quiet judgement.", longDescription: "A calm elevated spot that gives your cat the best seat in the room without taking over the room.", images: [img.catWindow, img.catBasket], colors: ["Oat", "Olive"], materials: "Oak-look wood, cotton canvas, steel fittings", dimensions: "55 × 35 cm", features: ["Strong window mounts", "Removable canvas cover", "Supports up to 12 kg", "Tool-free installation"], careInstructions: "Machine wash cover cold. Wipe frame clean.", featured: true },
  { ...common, id: "c2", slug: "woven-hideaway-basket", name: "The Woven Hideaway Basket", animal: "cat", category: "Sleep", price: 78, description: "A handwoven retreat that feels at home in the living room.", longDescription: "An airy cocoon with a soft inner cushion for cats who like a little privacy with their comfort.", images: [img.catBasket, img.catWindow], colors: ["Natural"], materials: "Natural water hyacinth, cotton cushion", dimensions: "42 × 42 × 38 cm", features: ["Handwoven texture", "Removable cushion", "Breathable construction", "Furniture-friendly base"], careInstructions: "Vacuum basket gently. Wash cushion cover cold.", featured: false },
  { ...common, id: "c3", slug: "clay-ceramic-bowl", name: "The Clay Ceramic Bowl", animal: "cat", category: "Feed", price: 28, description: "A low, whisker-friendly bowl finished by hand.", longDescription: "A softly imperfect ceramic bowl with a wide shallow shape designed for comfortable everyday feeding.", images: [img.catBowl, img.catLounge], colors: ["Clay", "Oat"], materials: "Food-safe glazed stoneware", dimensions: "16 cm diameter · 4 cm high", features: ["Whisker-friendly shape", "Weighted base", "Food-safe glaze", "Dishwasher safe"], careInstructions: "Dishwasher safe on a gentle cycle.", featured: true },
  { ...common, id: "c4", slug: "palm-scratching-lounge", name: "The Palm Scratching Lounge", animal: "cat", category: "Scratch", price: 46, description: "A sculptural scratcher, lounger and living-room peace treaty.", longDescription: "Curved for stretching and snoozing, with replaceable natural fibre surfaces and a considered furniture-like form.", images: [img.catLounge, img.catPlay], colors: ["Natural", "Charcoal"], materials: "Pressed wood, woven sisal", dimensions: "62 × 24 × 18 cm", features: ["Ergonomic curve", "Dense sisal surface", "Non-slip feet", "Replaceable scratch pad"], careInstructions: "Vacuum loose fibres. Keep dry.", featured: true },
  { ...common, id: "c5", slug: "feather-wand", name: "The Cedar Feather Wand", animal: "cat", category: "Play", price: 16, description: "A simple, beautiful wand made for daily hunting games.", longDescription: "A lightweight cedar handle and natural feather teaser for connection, movement and a little graceful chaos.", images: [img.catPlay, img.catWindow], colors: ["Cedar"], materials: "Cedar wood, cotton cord, natural feathers", dimensions: "45 cm wand", features: ["Balanced wood handle", "Replaceable teaser", "Plastic-free construction", "Easy to store"], careInstructions: "Store out of reach after supervised play.", featured: false },
];

export const getProduct = (slug: string) => products.find((product) => product.slug === slug);
export const productsFor = (animal: "dog" | "cat") => products.filter((product) => product.animal === animal);
